import type { AgentStep, Evidence, Report, SystemService, Task, TaskEvent } from "./types";

export const tasks: Task[] = [
  {
    task_id: "tsk_9A21",
    title: "Portable espresso maker competitor scan",
    target: "https://example.com/products/portable-espresso",
    mode: "complete_report",
    status: "reasoning",
    priority: "high",
    created_at: "2026-05-25T01:15:00+08:00",
    started_at: "2026-05-25T01:15:08+08:00",
    duration_ms: 184000,
    trace_id: "trc_8f31a29",
  },
  {
    task_id: "tsk_8B77",
    title: "Desk lamp poor review analysis",
    target: "demo://desk-lamp-reviews.csv",
    mode: "review_risk_scan",
    status: "completed",
    priority: "normal",
    created_at: "2026-05-24T22:40:00+08:00",
    started_at: "2026-05-24T22:40:09+08:00",
    finished_at: "2026-05-24T22:43:41+08:00",
    duration_ms: 212000,
    trace_id: "trc_f2ad390",
    report_id: "rpt_1024",
  },
  {
    task_id: "tsk_7C03",
    title: "Pet water fountain opportunity report",
    target: "demo://pet-fountain-reviews.json",
    mode: "opportunity_analysis",
    status: "reporting",
    priority: "normal",
    created_at: "2026-05-25T00:55:00+08:00",
    started_at: "2026-05-25T00:55:06+08:00",
    duration_ms: 326000,
    trace_id: "trc_7b4c1e3",
  },
  {
    task_id: "tsk_6D44",
    title: "USB-C hub crawler run",
    target: "https://example.com/products/usbc-hub",
    mode: "competitor_review",
    status: "failed",
    priority: "normal",
    created_at: "2026-05-24T21:10:00+08:00",
    started_at: "2026-05-24T21:10:04+08:00",
    finished_at: "2026-05-24T21:11:02+08:00",
    duration_ms: 58000,
    trace_id: "trc_35bfcc9",
  },
  {
    task_id: "tsk_5E19",
    title: "Smart scale return reason scan",
    target: "demo://smart-scale-reviews.csv",
    mode: "risk_scan",
    status: "completed",
    priority: "high",
    created_at: "2026-05-24T19:30:00+08:00",
    started_at: "2026-05-24T19:30:07+08:00",
    finished_at: "2026-05-24T19:34:22+08:00",
    duration_ms: 255000,
    trace_id: "trc_d302ee1",
    report_id: "rpt_1023",
  },
];

export const taskEvents: TaskEvent[] = [
  {
    event_id: "evt_001",
    task_id: "tsk_9A21",
    module: "api",
    event_type: "task.accepted",
    status: "received",
    message: "Task accepted and persisted.",
    created_at: "2026-05-25T01:15:00+08:00",
  },
  {
    event_id: "evt_002",
    task_id: "tsk_9A21",
    module: "worker",
    event_type: "task.started",
    status: "running",
    message: "Celery worker started Agent run.",
    created_at: "2026-05-25T01:15:08+08:00",
  },
  {
    event_id: "evt_003",
    task_id: "tsk_9A21",
    module: "crawler",
    event_type: "crawler.product_saved",
    status: "crawling",
    message: "Product page snapshot and extracted fields saved.",
    created_at: "2026-05-25T01:15:41+08:00",
  },
  {
    event_id: "evt_004",
    task_id: "tsk_9A21",
    module: "rag",
    event_type: "rag.retrieval",
    status: "retrieving",
    message: "Retrieved 8 review chunks for defect analysis.",
    created_at: "2026-05-25T01:17:12+08:00",
  },
  {
    event_id: "evt_005",
    task_id: "tsk_9A21",
    module: "agent",
    event_type: "agent.reasoning",
    status: "reasoning",
    message: "Agent is comparing defect clusters against opportunity criteria.",
    created_at: "2026-05-25T01:18:02+08:00",
  },
  {
    event_id: "evt_006",
    task_id: "tsk_6D44",
    module: "crawler",
    event_type: "crawler.failed",
    status: "failed",
    message: "PAGE_TIMEOUT while waiting for review container.",
    created_at: "2026-05-24T21:11:02+08:00",
  },
];

export const agentSteps: AgentStep[] = [
  {
    step_id: "stp_9A21_001",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 1,
    step_type: "thought",
    status: "success",
    duration_ms: 810,
    observation_summary: "User requested a complete competitor research report.",
  },
  {
    step_id: "stp_9A21_002",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 2,
    step_type: "action",
    tool_name: "crawl_product_tool",
    status: "success",
    duration_ms: 32900,
    input_summary: "Fetch product page and save screenshot artifacts.",
    observation_summary: "Saved title, price, rating summary, and 43 review snippets.",
  },
  {
    step_id: "stp_9A21_003",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 3,
    step_type: "action",
    tool_name: "search_reviews_tool",
    status: "success",
    duration_ms: 7800,
    input_summary: "Search for build quality, leakage, returns, and shipping complaints.",
    observation_summary: "Top defects: seal leakage, low battery life, slow support.",
  },
  {
    step_id: "stp_9A21_004",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 4,
    step_type: "self_check",
    status: "running",
    duration_ms: 420,
    observation_summary: "Validating evidence coverage before report generation.",
  },
  {
    step_id: "stp_6D44_002",
    agent_run_id: "run_6D44",
    task_id: "tsk_6D44",
    step_index: 2,
    step_type: "action",
    tool_name: "crawl_product_tool",
    status: "failed",
    duration_ms: 58000,
    input_summary: "Fetch USB-C hub page and reviews.",
    error_code: "PAGE_TIMEOUT",
    observation_summary: "Review container did not appear before timeout.",
  },
];

export const evidence: Evidence[] = [
  {
    evidence_id: "ev_1001",
    source_type: "review",
    source_url: "demo://portable-espresso/reviews/31",
    similarity: 0.91,
    rating: 2,
    content: "The seal started leaking after a week and support asked for a video twice.",
    task_id: "tsk_9A21",
    metadata: { cluster: "quality", language: "en" },
  },
  {
    evidence_id: "ev_1002",
    source_type: "review",
    source_url: "demo://portable-espresso/reviews/44",
    similarity: 0.87,
    rating: 1,
    content: "Battery life is nowhere near the listing. It failed during a short trip.",
    task_id: "tsk_9A21",
    metadata: { cluster: "battery", language: "en" },
  },
  {
    evidence_id: "ev_1003",
    source_type: "crawler_artifact",
    source_url: "artifact://tsk_9A21/product-page.png",
    similarity: 0.82,
    content: "Screenshot and DOM snapshot for the competitor product detail page.",
    task_id: "tsk_9A21",
    metadata: { artifact_type: "screenshot" },
  },
  {
    evidence_id: "ev_1004",
    source_type: "review",
    source_url: "demo://desk-lamp/reviews/18",
    similarity: 0.89,
    rating: 2,
    content: "The hinge loosens after a few days and the lamp head drops overnight.",
    task_id: "tsk_8B77",
    metadata: { cluster: "mechanical" },
  },
  {
    evidence_id: "ev_1005",
    source_type: "review",
    source_url: "demo://smart-scale/reviews/52",
    similarity: 0.85,
    rating: 1,
    content: "App pairing failed repeatedly and customer service only sent generic steps.",
    task_id: "tsk_5E19",
    metadata: { cluster: "app_support" },
  },
];

export const reports: Report[] = [
  {
    report_id: "rpt_1024",
    task_id: "tsk_8B77",
    title: "Desk lamp poor review analysis",
    summary:
      "The strongest defect cluster is mechanical durability. Users complain about hinge looseness, unstable brightness memory, and packaging damage.",
    risk_level: "medium",
    risk_score: 64,
    evidence_count: 16,
    created_at: "2026-05-24T22:43:41+08:00",
    sections: [
      {
        title: "Primary pain point",
        body: "Durability complaints concentrate around the hinge, which creates a clear product improvement opportunity.",
        evidence_ids: ["ev_1004"],
      },
      {
        title: "Positioning opportunity",
        body: "A reinforced hinge and explicit warranty messaging could separate a new entrant from low-cost competitors.",
        evidence_ids: ["ev_1004"],
      },
    ],
  },
  {
    report_id: "rpt_1023",
    task_id: "tsk_5E19",
    title: "Smart scale return reason scan",
    summary:
      "Returns are driven less by measurement accuracy and more by app pairing failures, onboarding confusion, and slow support loops.",
    risk_level: "high",
    risk_score: 78,
    evidence_count: 21,
    created_at: "2026-05-24T19:34:22+08:00",
    sections: [
      {
        title: "Support risk",
        body: "The app onboarding flow creates avoidable support demand. A simpler Bluetooth pairing path would reduce returns.",
        evidence_ids: ["ev_1005"],
      },
    ],
  },
];

export const services: SystemService[] = [
  { name: "API", status: "mock", detail: "Next.js mock client" },
  { name: "Redis", status: "offline", detail: "planned Day 05" },
  { name: "Celery Worker", status: "offline", detail: "planned Day 05" },
  { name: "PostgreSQL", status: "offline", detail: "planned Day 03" },
  { name: "pgvector", status: "offline", detail: "planned Day 14" },
  { name: "Crawler", status: "mock", detail: "Stitch reference available" },
  { name: "Agent", status: "mock", detail: "state machine planned" },
];
