import type { AgentStep, Evidence, Report, SystemService, Task, TaskEvent } from "./types";

export const tasks: Task[] = [
  {
    task_id: "tsk_9A21",
    title: "便携咖啡机竞品扫描",
    target: "https://example.com/products/portable-espresso",
    mode: "complete_report",
    status: "reasoning",
    priority: "high",
    created_at: "2026-05-25T01:15:00+08:00",
    started_at: "2026-05-25T01:15:08+08:00",
    duration_ms: 184000,
    trace_id: "trc_8f31a29",
  },
  {
    task_id: "tsk_8B77",
    title: "台灯差评分析",
    target: "demo://desk-lamp-reviews.csv",
    mode: "review_risk_scan",
    status: "completed",
    priority: "normal",
    created_at: "2026-05-24T22:40:00+08:00",
    started_at: "2026-05-24T22:40:09+08:00",
    finished_at: "2026-05-24T22:43:41+08:00",
    duration_ms: 212000,
    trace_id: "trc_f2ad390",
    report_id: "rpt_1024",
  },
  {
    task_id: "tsk_7C03",
    title: "宠物饮水机机会点报告",
    target: "demo://pet-fountain-reviews.json",
    mode: "opportunity_analysis",
    status: "reporting",
    priority: "normal",
    created_at: "2026-05-25T00:55:00+08:00",
    started_at: "2026-05-25T00:55:06+08:00",
    duration_ms: 326000,
    trace_id: "trc_7b4c1e3",
  },
  {
    task_id: "tsk_6D44",
    title: "USB-C 拓展坞采集任务",
    target: "https://example.com/products/usbc-hub",
    mode: "competitor_review",
    status: "failed",
    priority: "normal",
    created_at: "2026-05-24T21:10:00+08:00",
    started_at: "2026-05-24T21:10:04+08:00",
    finished_at: "2026-05-24T21:11:02+08:00",
    duration_ms: 58000,
    trace_id: "trc_35bfcc9",
  },
  {
    task_id: "tsk_5E19",
    title: "智能体脂秤退货原因扫描",
    target: "demo://smart-scale-reviews.csv",
    mode: "risk_scan",
    status: "completed",
    priority: "high",
    created_at: "2026-05-24T19:30:00+08:00",
    started_at: "2026-05-24T19:30:07+08:00",
    finished_at: "2026-05-24T19:34:22+08:00",
    duration_ms: 255000,
    trace_id: "trc_d302ee1",
    report_id: "rpt_1023",
  },
];

export const taskEvents: TaskEvent[] = [
  {
    event_id: "evt_001",
    task_id: "tsk_9A21",
    module: "api",
    event_type: "task.accepted",
    status: "received",
    message: "任务已接收并持久化。",
    created_at: "2026-05-25T01:15:00+08:00",
  },
  {
    event_id: "evt_002",
    task_id: "tsk_9A21",
    module: "worker",
    event_type: "task.started",
    status: "running",
    message: "Celery Worker 已启动 Agent 执行。",
    created_at: "2026-05-25T01:15:08+08:00",
  },
  {
    event_id: "evt_003",
    task_id: "tsk_9A21",
    module: "crawler",
    event_type: "crawler.product_saved",
    status: "crawling",
    message: "商品页快照和抽取字段已保存。",
    created_at: "2026-05-25T01:15:41+08:00",
  },
  {
    event_id: "evt_004",
    task_id: "tsk_9A21",
    module: "rag",
    event_type: "rag.retrieval",
    status: "retrieving",
    message: "已召回 8 条评论切片用于缺陷分析。",
    created_at: "2026-05-25T01:17:12+08:00",
  },
  {
    event_id: "evt_005",
    task_id: "tsk_9A21",
    module: "agent",
    event_type: "agent.reasoning",
    status: "reasoning",
    message: "Agent 正在对照机会点评估标准比较缺陷聚类。",
    created_at: "2026-05-25T01:18:02+08:00",
  },
  {
    event_id: "evt_006",
    task_id: "tsk_6D44",
    module: "crawler",
    event_type: "crawler.failed",
    status: "failed",
    message: "等待评论容器时发生 PAGE_TIMEOUT。",
    created_at: "2026-05-24T21:11:02+08:00",
  },
];

export const agentSteps: AgentStep[] = [
  {
    step_id: "stp_9A21_001",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 1,
    step_type: "thought",
    status: "success",
    duration_ms: 810,
    observation_summary: "用户请求生成完整竞品调研报告。",
  },
  {
    step_id: "stp_9A21_002",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 2,
    step_type: "action",
    tool_name: "crawl_product_tool",
    status: "success",
    duration_ms: 32900,
    input_summary: "抓取商品页并保存截图 artifact。",
    observation_summary: "已保存标题、价格、评分摘要和 43 条评论片段。",
  },
  {
    step_id: "stp_9A21_003",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 3,
    step_type: "action",
    tool_name: "search_reviews_tool",
    status: "success",
    duration_ms: 7800,
    input_summary: "检索做工质量、漏液、退货和物流投诉。",
    observation_summary: "主要缺陷：密封漏液、电池续航短、客服响应慢。",
  },
  {
    step_id: "stp_9A21_004",
    agent_run_id: "run_9A21",
    task_id: "tsk_9A21",
    step_index: 4,
    step_type: "self_check",
    status: "running",
    duration_ms: 420,
    observation_summary: "生成报告前正在校验证据覆盖度。",
  },
  {
    step_id: "stp_6D44_002",
    agent_run_id: "run_6D44",
    task_id: "tsk_6D44",
    step_index: 2,
    step_type: "action",
    tool_name: "crawl_product_tool",
    status: "failed",
    duration_ms: 58000,
    input_summary: "抓取 USB-C 拓展坞页面和评论。",
    error_code: "PAGE_TIMEOUT",
    observation_summary: "评论容器在超时前没有出现。",
  },
];

export const evidence: Evidence[] = [
  {
    evidence_id: "ev_1001",
    source_type: "review",
    source_url: "demo://portable-espresso/reviews/31",
    similarity: 0.91,
    rating: 2,
    content: "密封圈一周后开始漏水，客服两次要求补发视频。",
    task_id: "tsk_9A21",
    metadata: { cluster: "quality", language: "en" },
  },
  {
    evidence_id: "ev_1002",
    source_type: "review",
    source_url: "demo://portable-espresso/reviews/44",
    similarity: 0.87,
    rating: 1,
    content: "续航远低于商品页描述，短途旅行中就没电了。",
    task_id: "tsk_9A21",
    metadata: { cluster: "battery", language: "en" },
  },
  {
    evidence_id: "ev_1003",
    source_type: "crawler_artifact",
    source_url: "artifact://tsk_9A21/product-page.png",
    similarity: 0.82,
    content: "竞品商品详情页的截图和 DOM 快照。",
    task_id: "tsk_9A21",
    metadata: { artifact_type: "screenshot" },
  },
  {
    evidence_id: "ev_1004",
    source_type: "review",
    source_url: "demo://desk-lamp/reviews/18",
    similarity: 0.89,
    rating: 2,
    content: "转轴几天后就松动，灯头会在夜里自己下垂。",
    task_id: "tsk_8B77",
    metadata: { cluster: "mechanical" },
  },
  {
    evidence_id: "ev_1005",
    source_type: "review",
    source_url: "demo://smart-scale/reviews/52",
    similarity: 0.85,
    rating: 1,
    content: "App 多次配对失败，客服只发送通用操作步骤。",
    task_id: "tsk_5E19",
    metadata: { cluster: "app_support" },
  },
];

export const reports: Report[] = [
  {
    report_id: "rpt_1024",
    task_id: "tsk_8B77",
    title: "台灯差评分析",
    summary:
      "最集中的缺陷聚类是机械耐用性。用户反复提到转轴松动、亮度记忆不稳定和包装破损。",
    risk_level: "medium",
    risk_score: 64,
    evidence_count: 16,
    created_at: "2026-05-24T22:43:41+08:00",
    sections: [
      {
        title: "主要痛点",
        body: "耐用性投诉集中在转轴结构，这为产品改进提供了明确机会。",
        evidence_ids: ["ev_1004"],
      },
      {
        title: "定位机会",
        body: "强化转轴并明确质保承诺，可以让新品和低价竞品形成差异。",
        evidence_ids: ["ev_1004"],
      },
    ],
  },
  {
    report_id: "rpt_1023",
    task_id: "tsk_5E19",
    title: "智能体脂秤退货原因扫描",
    summary:
      "退货原因更多来自 App 配对失败、上手流程混乱和客服响应慢，而不是测量准确性本身。",
    risk_level: "high",
    risk_score: 78,
    evidence_count: 21,
    created_at: "2026-05-24T19:34:22+08:00",
    sections: [
      {
        title: "售后风险",
        body: "App 上手流程制造了可避免的售后需求。更简单的蓝牙配对路径能降低退货。",
        evidence_ids: ["ev_1005"],
      },
    ],
  },
];

export const services: SystemService[] = [
  { name: "API", status: "mock", detail: "Next.js 模拟客户端" },
  { name: "Redis", status: "offline", detail: "Day 05 已规划" },
  { name: "Celery Worker", status: "offline", detail: "Day 05 已规划" },
  { name: "PostgreSQL", status: "offline", detail: "Day 03 已规划" },
  { name: "pgvector", status: "offline", detail: "Day 14 已规划" },
  { name: "Crawler", status: "mock", detail: "Stitch 参考稿可用" },
  { name: "Agent", status: "mock", detail: "状态机已接入" },
];
